### ISSUE TITLE
using var c = new Context();

### ISSUE THREAD

**Issue by SadikSunbul** [feyzabakir/Portfolio_Core#1]
1->Bu kullanım sunucusi için gereksiz bağlantı açma ve kapama işlemleriyle sonuçlanabilir. Bu, yüksek işlem yoğunluğu olan uygulamalarda performans sorunlarına yol açabilir.

2-> İşlemler arasındaki bağlantı izolasyonu, bazı eş zamanlılık sorunlarına yol açabilir. Örneğin, bir işlem verileri güncellediğinde, diğer işlemlerin aynı verilere erişimini kısıtlayabilir.

3->Change Tracking Sorunları , her bağlam nesnesi kendi değişiklik izleme mekanizmasını kullanır. Bu nedenle bir bağlam nesnesi üzerinde değişiklik yaptığınızda, diğer bağlam nesneleri bu değişiklikleri otomatik olarak takip etmez. Bu, aynı nesneler üzerinde aynı anda çalışan farklı bağlam nesneleri için sorunlara yol açabilir.
 Tek bir bağlam nesnesini paylaşarak çalışmak, aynı nesneler üzerinde yapılan değişiklikleri izlemek ve işlemek için daha uygun olabilir. Ancak işlem izolasyonu ve hafıza verimliliği gibi faktörleri göz önünde bulundurarak karar vermelisiniz.

private readonly Context _dbContext;
        public GenericRepository()
        {
            _dbContext = new Context();
        }

Bu kullanım daha dogru olucaktır

**Comment by feyzabakir** [comment]
Önerileriniz için teşekkür ederim. Kodun performans ve veritabanı bağlamındaki sorunları yeniden değerlendireceğim.
